# Default values for votingapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


deployment:
  name: voting-app-deploy
  replicaCount: 1
  image: dockersamples/examplevotingapp_vote
    
    
service:
  name: voting-svc
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30001

entireAppLabel: 
  app: demo-voting-app