# Default values for postgresapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



deployment:
  name: postgres-deploy
  image: coreroller/postgres
  replicaCount: 1   

service:
  name: postgres-svc
  type: ClusterIP
  port: 5432
  targetPort: 5432

entireAppLabel:
  app: demo-voting-app

