apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.entireAppLabel.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "selectorLabels" .| nindent 6 }}
  template:
    metadata:
      name: worker-app-pod
      labels:
        {{- include "selectorLabels" .| nindent 8 }}

    spec:
      containers:
        - name: worker-app
          image: {{ .Values.deployment.image }}