apiVersion: v1
kind: Service
metadata:
  name: db-svc
  labels:
    app: {{ .Values.entireAppLabel.app }}

spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

  selector:
    {{- include "postSelectorLabels" .| nindent 4 }}
